services:
  - type: web
    name: passport-index-api
    env: go
    plan: free
    buildCommand: go build -o app ./cmd/passport-api
    startCommand: ./app
    envVars:
      - key: PORT
        value: 8080
